### ISSUE TITLE
Do you plan to change this script for the newest version - 2.8.0?

### ISSUE THREAD

**Issue by ixolt** [Icinga/icinga2-api-examples#5]
https://github.com/Icinga/icinga2-api-examples/blob/941d3ab20741e88e8ffd7597c5f9c627c4a270ea/aws-ec2/icinga2_ec2#L121
https://github.com/Icinga/icinga2-api-examples/blob/941d3ab20741e88e8ffd7597c5f9c627c4a270ea/aws-ec2/icinga2_ec2#L123
https://github.com/Icinga/icinga2-api-examples/blob/941d3ab20741e88e8ffd7597c5f9c627c4a270ea/aws-ec2/icinga2_ec2#L124
https://github.com/Icinga/icinga2-api-examples/blob/941d3ab20741e88e8ffd7597c5f9c627c4a270ea/aws-ec2/icinga2_ec2#L125

it should be changed from pki to /var/lib/icinga2/certs

**Comment by dnsmichi** [comment]
Please send in a PR.

**Comment by dnsmichi** [comment]
It is using relative paths anyways, there's no relation to Icinga 2.8 here. I'm closing therefore.
